### ISSUE TITLE
Problem with fastlane

### ISSUE THREAD

**Issue by danielkiedrowski** [onesky/onesky-ruby#12]
Hello,
I used your ruby gem to develop a fastlane plugin, to download and upload texts from and to onesky. Unfortunately there is a conflicht with your gems, when using a newer fastlane version than 2.38.1.

```
fastlane (~> 2.55.0) was resolved to 2.55.0, which depends on
      google-api-client (< 0.14.0, >= 0.13.1) was resolved to 0.13.1, which depends on
        mime-types (~> 3.0)

fastlane-plugin-onesky was resolved to 0.2.1, which depends on
      onesky-ruby was resolved to 1.0.1, which depends on
        rest-client (~> 1.8) was resolved to 1.8.0, which depends on
          mime-types (< 3.0, >= 1.16)
```

Could you please update your dependency of rest-client to 2.x so that the mime types can be > 3.0.

Thank you.

**Comment by danielkiedrowski** [comment]
I just filed a pull request. I updated the rest-client to something 2.0 and updated the tests. #13

**Comment by VLMH** [comment]
#13 merged
